//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktuppgiften togs bort..
        /// </summary>
        internal static string Action_Contact_Deleted {
            get {
                return ResourceManager.GetString("Action_Contact_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktuppgiften sparades..
        /// </summary>
        internal static string Action_Contact_Saved {
            get {
                return ResourceManager.GetString("Action_Contact_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden togs bort..
        /// </summary>
        internal static string Action_Customer_Deleted {
            get {
                return ResourceManager.GetString("Action_Customer_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunden sparades..
        /// </summary>
        internal static string Action_Customer_Saved {
            get {
                return ResourceManager.GetString("Action_Customer_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okänd händelse..
        /// </summary>
        internal static string Action_Unknown {
            get {
                return ResourceManager.GetString("Action_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakttypens benämning kan bestå av som mest 50 tecken..
        /// </summary>
        internal static string ContactType_Name_MaxLength {
            get {
                return ResourceManager.GetString("ContactType_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakttypens benämning måste anges..
        /// </summary>
        internal static string ContactType_Name_Required {
            get {
                return ResourceManager.GetString("ContactType_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kunduppgifttyperna skulle hämtas..
        /// </summary>
        internal static string ContactType_Selecting_Error {
            get {
                return ResourceManager.GetString("ContactType_Selecting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kunduppgiften skulle tas bort..
        /// </summary>
        internal static string Contact_Deleting_Error {
            get {
                return ResourceManager.GetString("Contact_Deleting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kontaktuppgiften skulle läggas till..
        /// </summary>
        internal static string Contact_Inserting_Error {
            get {
                return ResourceManager.GetString("Contact_Inserting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade då kontaktuppgiften skulle läggas till..
        /// </summary>
        internal static string Contact_Inserting_Unexpected_Error {
            get {
                return ResourceManager.GetString("Contact_Inserting_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktuppgiften med nummer {0} hittades inte..
        /// </summary>
        internal static string Contact_Not_Found {
            get {
                return ResourceManager.GetString("Contact_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kunduppgifterna skulle hämtas..
        /// </summary>
        internal static string Contact_Selecting_Error {
            get {
                return ResourceManager.GetString("Contact_Selecting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kontaktuppgiften skulle uppdateras..
        /// </summary>
        internal static string Contact_Updating_Error {
            get {
                return ResourceManager.GetString("Contact_Updating_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett oväntat fel inträffade då kontaktuppgiften skulle uppdateras..
        /// </summary>
        internal static string Contact_Updating_Unexpected_Error {
            get {
                return ResourceManager.GetString("Contact_Updating_Unexpected_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformationen kan bestå av som mest 50 tecken..
        /// </summary>
        internal static string Contact_Value_MaxLength {
            get {
                return ResourceManager.GetString("Contact_Value_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontaktinformation måste anges..
        /// </summary>
        internal static string Contact_Value_Required {
            get {
                return ResourceManager.GetString("Contact_Value_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adressen kan bestå av som mest 30 tecken..
        /// </summary>
        internal static string Customer_Address_MaxLength {
            get {
                return ResourceManager.GetString("Customer_Address_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En adress måste anges..
        /// </summary>
        internal static string Customer_Address_Required {
            get {
                return ResourceManager.GetString("Customer_Address_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orten kan bestå av som mest 30 tecken..
        /// </summary>
        internal static string Customer_City_MaxLength {
            get {
                return ResourceManager.GetString("Customer_City_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En ort måste anges..
        /// </summary>
        internal static string Customer_City_Required {
            get {
                return ResourceManager.GetString("Customer_City_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort &apos;{0}&apos;?.
        /// </summary>
        internal static string Customer_Delete_Confirm {
            get {
                return ResourceManager.GetString("Customer_Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kunden skulle tas bort..
        /// </summary>
        internal static string Customer_Deleting_Error {
            get {
                return ResourceManager.GetString("Customer_Deleting_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namnet kan bestå av som mest 30 tecken..
        /// </summary>
        internal static string Customer_Name_MaxLength {
            get {
                return ResourceManager.GetString("Customer_Name_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett namn måste anges..
        /// </summary>
        internal static string Customer_Name_Required {
            get {
                return ResourceManager.GetString("Customer_Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postnumret verkar inte vara korrekt..
        /// </summary>
        internal static string Customer_PostalCode_Invalid_Format {
            get {
                return ResourceManager.GetString("Customer_PostalCode_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett postnummer måste anges..
        /// </summary>
        internal static string Customer_PostalCode_Required {
            get {
                return ResourceManager.GetString("Customer_PostalCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade då kunden skulle sparas..
        /// </summary>
        internal static string Customer_Saving_Error {
            get {
                return ResourceManager.GetString("Customer_Saving_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kontaktuppgiften.
        /// </summary>
        internal static string Data_Type_Contact {
            get {
                return ResourceManager.GetString("Data_Type_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kunden.
        /// </summary>
        internal static string Data_Type_Customer {
            get {
                return ResourceManager.GetString("Data_Type_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett fel inträffade i dataåtkomstlagret..
        /// </summary>
        internal static string Generic_DAL_Error_Message {
            get {
                return ResourceManager.GetString("Generic_DAL_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[1-9]\d{2} ?\d{2}$.
        /// </summary>
        internal static string Regular_Expression_PostalCode {
            get {
                return ResourceManager.GetString("Regular_Expression_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fel inträffade. Korrigera det som är fel och försök igen..
        /// </summary>
        internal static string Validation_Header {
            get {
                return ResourceManager.GetString("Validation_Header", resourceCulture);
            }
        }
    }
}
